//------------------------------------------------------------------------------
// AXI4-Lite Driver - Generated by UVMForge
//------------------------------------------------------------------------------

class axi4lite_driver extends uvm_driver #(axi4lite_seq_item);
    
    `uvm_component_utils(axi4lite_driver)
    
    virtual axi4lite_if.master vif;
    
    function new(string name = "axi4lite_driver", uvm_component parent = null);
        super.new(name, parent);
    endfunction
    
    virtual function void build_phase(uvm_phase phase);
        super.build_phase(phase);
        if (!uvm_config_db#(virtual axi4lite_if.master)::get(this, "", "vif", vif))
            `uvm_fatal(get_type_name(), "Virtual interface not found")
    endfunction
    
    virtual task run_phase(uvm_phase phase);
        axi4lite_seq_item req;
        
        reset_signals();
        @(posedge vif.clk);
        wait(vif.rst_n);
        
        forever begin
            seq_item_port.get_next_item(req);
            if (req.trans_type == AXI_WRITE)
                drive_write(req);
            else
                drive_read(req);
            seq_item_port.item_done();
        end
    endtask
    
    virtual task reset_signals();
        vif.master_cb.awvalid <= 1'b0;
        vif.master_cb.wvalid  <= 1'b0;
        vif.master_cb.bready  <= 1'b0;
        vif.master_cb.arvalid <= 1'b0;
        vif.master_cb.rready  <= 1'b0;
    endtask
    
    virtual task drive_write(axi4lite_seq_item req);
        // Write Address and Data phase (can be parallel)
        fork
            begin  // Address channel
                @(vif.master_cb);
                vif.master_cb.awaddr  <= req.addr;
                vif.master_cb.awprot  <= req.prot;
                vif.master_cb.awvalid <= 1'b1;
                do @(vif.master_cb);
                while (!vif.master_cb.awready);
                vif.master_cb.awvalid <= 1'b0;
            end
            begin  // Data channel
                @(vif.master_cb);
                vif.master_cb.wdata  <= req.data;
                vif.master_cb.wstrb  <= req.strb;
                vif.master_cb.wvalid <= 1'b1;
                do @(vif.master_cb);
                while (!vif.master_cb.wready);
                vif.master_cb.wvalid <= 1'b0;
            end
        join
        
        // Response phase
        vif.master_cb.bready <= 1'b1;
        do @(vif.master_cb);
        while (!vif.master_cb.bvalid);
        req.resp = axi_resp_e'(vif.master_cb.bresp);
        vif.master_cb.bready <= 1'b0;
        
        `uvm_info(get_type_name(), $sformatf("WRITE: %s", req.convert2string()), UVM_HIGH)
    endtask
    
    virtual task drive_read(axi4lite_seq_item req);
        // Address phase
        @(vif.master_cb);
        vif.master_cb.araddr  <= req.addr;
        vif.master_cb.arprot  <= req.prot;
        vif.master_cb.arvalid <= 1'b1;
        do @(vif.master_cb);
        while (!vif.master_cb.arready);
        vif.master_cb.arvalid <= 1'b0;
        
        // Data phase
        vif.master_cb.rready <= 1'b1;
        do @(vif.master_cb);
        while (!vif.master_cb.rvalid);
        req.rdata = vif.master_cb.rdata;
        req.resp  = axi_resp_e'(vif.master_cb.rresp);
        vif.master_cb.rready <= 1'b0;
        
        `uvm_info(get_type_name(), $sformatf("READ: %s", req.convert2string()), UVM_HIGH)
    endtask
    
endclass : axi4lite_driver