//------------------------------------------------------------------------------
// AXI4-Lite Sequence Library - Generated by VerifAI
//------------------------------------------------------------------------------

class axi4lite_base_seq extends uvm_sequence #(axi4lite_seq_item);
    `uvm_object_utils(axi4lite_base_seq)
    
    function new(string name = "axi4lite_base_seq");
        super.new(name);
    endfunction
    
    virtual task write(bit [32-1:0] addr, bit [32-1:0] data);
        axi4lite_seq_item req = axi4lite_seq_item::type_id::create("req");
        start_item(req);
        req.trans_type = AXI_WRITE;
        req.addr = addr;
        req.data = data;
        req.strb = '1;
        finish_item(req);
    endtask
    
    virtual task read(bit [32-1:0] addr, output bit [32-1:0] data);
        axi4lite_seq_item req = axi4lite_seq_item::type_id::create("req");
        start_item(req);
        req.trans_type = AXI_READ;
        req.addr = addr;
        finish_item(req);
        data = req.rdata;
    endtask
endclass : axi4lite_base_seq

class axi4lite_random_seq extends axi4lite_base_seq;
    `uvm_object_utils(axi4lite_random_seq)
    rand int num_trans;
    constraint num_trans_c { num_trans inside {[10:50]}; }
    
    function new(string name = "axi4lite_random_seq");
        super.new(name);
    endfunction
    
    virtual task body();
        axi4lite_seq_item req;
        `uvm_info(get_type_name(), $sformatf("Running %0d transactions", num_trans), UVM_MEDIUM)
        repeat (num_trans) begin
            req = axi4lite_seq_item::type_id::create("req");
            start_item(req);
            assert(req.randomize());
            finish_item(req);
        end
    endtask
endclass : axi4lite_random_seq

class axi4lite_reg_seq extends axi4lite_base_seq;
    `uvm_object_utils(axi4lite_reg_seq)
    
    function new(string name = "axi4lite_reg_seq");
        super.new(name);
    endfunction
    
    virtual task body();
        bit [32-1:0] rdata;
        `uvm_info(get_type_name(), "Testing all registers", UVM_MEDIUM)
        read('h00, rdata);
        `uvm_info(get_type_name(), $sformatf("STATUS = 0x%0h", rdata), UVM_MEDIUM)
        write('h04, 32'hDEAD_BEEF);
        read('h04, rdata);
        `uvm_info(get_type_name(), $sformatf("CONTROL = 0x%0h", rdata), UVM_MEDIUM)
        write('h08, 32'hDEAD_BEEF);
        read('h08, rdata);
        `uvm_info(get_type_name(), $sformatf("DATA = 0x%0h", rdata), UVM_MEDIUM)
    endtask
endclass : axi4lite_reg_seq
