//------------------------------------------------------------------------------
// AXI4-Lite Monitor - Generated by VerifAI
//------------------------------------------------------------------------------

class axi4lite_monitor extends uvm_monitor;
    
    `uvm_component_utils(axi4lite_monitor)
    
    virtual axi4lite_if.monitor vif;
    uvm_analysis_port #(axi4lite_seq_item) ap;
    
    function new(string name = "axi4lite_monitor", uvm_component parent = null);
        super.new(name, parent);
        ap = new("ap", this);
    endfunction
    
    virtual function void build_phase(uvm_phase phase);
        super.build_phase(phase);
        if (!uvm_config_db#(virtual axi4lite_if.monitor)::get(this, "", "vif", vif))
            `uvm_fatal(get_type_name(), "Virtual interface not found")
    endfunction
    
    virtual task run_phase(uvm_phase phase);
        @(posedge vif.clk);
        wait(vif.rst_n);
        
        fork
            monitor_writes();
            monitor_reads();
        join
    endtask
    
    virtual task monitor_writes();
        axi4lite_seq_item txn;
        bit [32-1:0] addr;
        bit [32-1:0] data;
        bit [4-1:0] strb;
        
        forever begin
            // Wait for write address
            @(vif.monitor_cb);
            if (vif.monitor_cb.awvalid && vif.monitor_cb.awready) begin
                addr = vif.monitor_cb.awaddr;
                
                // Wait for write data
                while (!(vif.monitor_cb.wvalid && vif.monitor_cb.wready))
                    @(vif.monitor_cb);
                data = vif.monitor_cb.wdata;
                strb = vif.monitor_cb.wstrb;
                
                // Wait for response
                while (!(vif.monitor_cb.bvalid && vif.monitor_cb.bready))
                    @(vif.monitor_cb);
                
                txn = axi4lite_seq_item::type_id::create("txn");
                txn.trans_type = AXI_WRITE;
                txn.addr = addr;
                txn.data = data;
                txn.strb = strb;
                txn.resp = axi_resp_e'(vif.monitor_cb.bresp);
                
                ap.write(txn);
                `uvm_info(get_type_name(), $sformatf("MON WRITE: %s", txn.convert2string()), UVM_HIGH)
            end
        end
    endtask
    
    virtual task monitor_reads();
        axi4lite_seq_item txn;
        bit [32-1:0] addr;
        
        forever begin
            @(vif.monitor_cb);
            if (vif.monitor_cb.arvalid && vif.monitor_cb.arready) begin
                addr = vif.monitor_cb.araddr;
                
                // Wait for read data
                while (!(vif.monitor_cb.rvalid && vif.monitor_cb.rready))
                    @(vif.monitor_cb);
                
                txn = axi4lite_seq_item::type_id::create("txn");
                txn.trans_type = AXI_READ;
                txn.addr = addr;
                txn.rdata = vif.monitor_cb.rdata;
                txn.resp = axi_resp_e'(vif.monitor_cb.rresp);
                
                ap.write(txn);
                `uvm_info(get_type_name(), $sformatf("MON READ: %s", txn.convert2string()), UVM_HIGH)
            end
        end
    endtask
    
endclass : axi4lite_monitor