//------------------------------------------------------------------------------
// AXI4-Lite Package - Generated by VerifAI
//------------------------------------------------------------------------------

package axi4lite_pkg;
    
    import uvm_pkg::*;
    `include "uvm_macros.svh"
    
    // AXI Response types
    typedef enum logic [1:0] {
        AXI_OKAY   = 2'b00,
        AXI_EXOKAY = 2'b01,
        AXI_SLVERR = 2'b10,
        AXI_DECERR = 2'b11
    } axi_resp_e;
    
    // Transaction type
    typedef enum bit {
        AXI_READ  = 1'b0,
        AXI_WRITE = 1'b1
    } axi_trans_type_e;
    
    // Parameters
    parameter int AXI_ADDR_WIDTH = 32;
    parameter int AXI_DATA_WIDTH = 32;
    parameter int AXI_STRB_WIDTH = 4;
    
    // Include components
    `include "axi4lite_seq_item.sv"
    `include "axi4lite_driver.sv"
    `include "axi4lite_monitor.sv"
    `include "axi4lite_sequencer.sv"
    `include "axi4lite_agent.sv"
    `include "axi4lite_seq_lib.sv"
    `include "axi4lite_scoreboard.sv"
    `include "axi4lite_coverage.sv"
    `include "axi4lite_env.sv"
    `include "axi4lite_base_test.sv"
    
endpackage : axi4lite_pkg