//------------------------------------------------------------------------------
// AXI4-Lite Coverage - Generated by UVMForge
//------------------------------------------------------------------------------

class axi4lite_coverage extends uvm_subscriber #(axi4lite_seq_item);
    `uvm_component_utils(axi4lite_coverage)
    
    axi4lite_seq_item txn;
    
    covergroup axi_cg;
        option.per_instance = 1;
        
        trans_type_cp: coverpoint txn.trans_type {
            bins read  = {AXI_READ};
            bins write = {AXI_WRITE};
        }
        
        address_cp: coverpoint txn.addr {
            bins status = {'h00};
            bins control = {'h04};
            bins data = {'h08};
            bins other = default;
        }
        
        response_cp: coverpoint txn.resp {
            bins okay   = {AXI_OKAY};
            bins slverr = {AXI_SLVERR};
            bins decerr = {AXI_DECERR};
        }
        
        addr_x_type: cross address_cp, trans_type_cp;
    endgroup
    
    function new(string name = "axi4lite_coverage", uvm_component parent = null);
        super.new(name, parent);
        axi_cg = new();
    endfunction
    
    virtual function void write(axi4lite_seq_item t);
        txn = t;
        axi_cg.sample();
    endfunction
    
    virtual function void report_phase(uvm_phase phase);
        `uvm_info(get_type_name(), $sformatf("Coverage: %.2f%%", axi_cg.get_coverage()), UVM_NONE)
    endfunction
endclass : axi4lite_coverage