//------------------------------------------------------------------------------
// AXI4-Lite Agent - Generated by VerifAI
//------------------------------------------------------------------------------

class axi4lite_agent extends uvm_agent;
    
    `uvm_component_utils(axi4lite_agent)
    
    axi4lite_driver    driver;
    axi4lite_monitor   monitor;
    axi4lite_sequencer sequencer;
    
    uvm_analysis_port #(axi4lite_seq_item) ap;
    bit is_active = 1;
    
    function new(string name = "axi4lite_agent", uvm_component parent = null);
        super.new(name, parent);
    endfunction
    
    virtual function void build_phase(uvm_phase phase);
        super.build_phase(phase);
        monitor = axi4lite_monitor::type_id::create("monitor", this);
        if (is_active == UVM_ACTIVE) begin
            driver    = axi4lite_driver::type_id::create("driver", this);
            sequencer = axi4lite_sequencer::type_id::create("sequencer", this);
        end
    endfunction
    
    virtual function void connect_phase(uvm_phase phase);
        super.connect_phase(phase);
        ap = monitor.ap;
        if (is_active == UVM_ACTIVE)
            driver.seq_item_port.connect(sequencer.seq_item_export);
    endfunction
    
endclass : axi4lite_agent