//------------------------------------------------------------------------------
// AXI4-Lite Base Test - Generated by VerifAI
//------------------------------------------------------------------------------

class axi4lite_base_test extends uvm_test;
    `uvm_component_utils(axi4lite_base_test)
    
    axi4lite_env env;
    
    function new(string name = "axi4lite_base_test", uvm_component parent = null);
        super.new(name, parent);
    endfunction
    
    virtual function void build_phase(uvm_phase phase);
        super.build_phase(phase);
        env = axi4lite_env::type_id::create("env", this);
    endfunction
    
    virtual function void end_of_elaboration_phase(uvm_phase phase);
        uvm_top.print_topology();
    endfunction
    
    virtual task run_phase(uvm_phase phase);
        axi4lite_random_seq seq;
        phase.raise_objection(this);
        seq = axi4lite_random_seq::type_id::create("seq");
        seq.start(env.agent.sequencer);
        #100ns;
        phase.drop_objection(this);
    endtask
endclass : axi4lite_base_test

class axi4lite_reg_test extends axi4lite_base_test;
    `uvm_component_utils(axi4lite_reg_test)
    
    function new(string name = "axi4lite_reg_test", uvm_component parent = null);
        super.new(name, parent);
    endfunction
    
    virtual task run_phase(uvm_phase phase);
        axi4lite_reg_seq seq;
        phase.raise_objection(this);
        seq = axi4lite_reg_seq::type_id::create("seq");
        seq.start(env.agent.sequencer);
        #100ns;
        phase.drop_objection(this);
    endtask
endclass : axi4lite_reg_test
