//------------------------------------------------------------------------------
// AXI4-Lite Interface - Generated by VerifAI
//------------------------------------------------------------------------------

interface axi4lite_if (input logic clk, input logic rst_n);
    
    // Write Address Channel
    logic [32-1:0]  awaddr;
    logic                         awvalid;
    logic                         awready;
    logic [2:0]                   awprot;
    
    // Write Data Channel
    logic [32-1:0]  wdata;
    logic [4-1:0]  wstrb;
    logic                         wvalid;
    logic                         wready;
    
    // Write Response Channel
    logic [1:0]                   bresp;
    logic                         bvalid;
    logic                         bready;
    
    // Read Address Channel
    logic [32-1:0]  araddr;
    logic                         arvalid;
    logic                         arready;
    logic [2:0]                   arprot;
    
    // Read Data Channel
    logic [32-1:0]  rdata;
    logic [1:0]                   rresp;
    logic                         rvalid;
    logic                         rready;
    
    // Master Clocking Block
    clocking master_cb @(posedge clk);
        default input #1 output #1;
        // Write Address
        output awaddr, awvalid, awprot;
        input  awready;
        // Write Data
        output wdata, wstrb, wvalid;
        input  wready;
        // Write Response
        input  bresp, bvalid;
        output bready;
        // Read Address
        output araddr, arvalid, arprot;
        input  arready;
        // Read Data
        input  rdata, rresp, rvalid;
        output rready;
    endclocking
    
    // Monitor Clocking Block
    clocking monitor_cb @(posedge clk);
        default input #1;
        input awaddr, awvalid, awready, awprot;
        input wdata, wstrb, wvalid, wready;
        input bresp, bvalid, bready;
        input araddr, arvalid, arready, arprot;
        input rdata, rresp, rvalid, rready;
    endclocking
    
    // Modports
    modport master (clocking master_cb, input clk, rst_n);
    modport monitor (clocking monitor_cb, input clk, rst_n);
    
endinterface : axi4lite_if