//------------------------------------------------------------------------------
// AXI4-Lite Scoreboard - Generated by VerifAI
//------------------------------------------------------------------------------

class axi4lite_scoreboard extends uvm_scoreboard;
    `uvm_component_utils(axi4lite_scoreboard)
    
    uvm_analysis_imp #(axi4lite_seq_item, axi4lite_scoreboard) ap;
    bit [32-1:0] reg_model[bit [32-1:0]];
    
    int num_writes, num_reads, num_errors, num_matches;
    
    function new(string name = "axi4lite_scoreboard", uvm_component parent = null);
        super.new(name, parent);
        ap = new("ap", this);
    endfunction
    
    virtual function void build_phase(uvm_phase phase);
        super.build_phase(phase);
        reg_model['h00] = 'h00000000;
        reg_model['h04] = 'h00000000;
        reg_model['h08] = 'h00000000;
    endfunction
    
    virtual function void write(axi4lite_seq_item txn);
        if (txn.trans_type == AXI_WRITE) begin
            num_writes++;
            if (is_writable(txn.addr))
                reg_model[txn.addr] = txn.data;
        end else begin
            num_reads++;
            if (reg_model.exists(txn.addr)) begin
                if (txn.rdata === reg_model[txn.addr]) begin
                    num_matches++;
                end else begin
                    num_errors++;
                    `uvm_error(get_type_name(), $sformatf("MISMATCH @ 0x%0h: exp=0x%0h got=0x%0h",
                        txn.addr, reg_model[txn.addr], txn.rdata))
                end
            end
        end
    endfunction
    
    virtual function bit is_writable(bit [32-1:0] addr);
        case (addr)
            'h00: return 0;
            'h04: return 1;
            'h08: return 1;
            default: return 1;
        endcase
    endfunction
    
    virtual function void report_phase(uvm_phase phase);
        `uvm_info(get_type_name(), "===== SCOREBOARD SUMMARY =====", UVM_NONE)
        `uvm_info(get_type_name(), $sformatf("Writes: %0d, Reads: %0d", num_writes, num_reads), UVM_NONE)
        `uvm_info(get_type_name(), $sformatf("Matches: %0d, Errors: %0d", num_matches, num_errors), UVM_NONE)
        if (num_errors > 0)
            `uvm_error(get_type_name(), "TEST FAILED")
        else
            `uvm_info(get_type_name(), "TEST PASSED", UVM_NONE)
    endfunction
endclass : axi4lite_scoreboard