//------------------------------------------------------------------------------
// AXI4-Lite Sequence Item - Generated by UVMForge
//------------------------------------------------------------------------------

class axi4lite_seq_item extends uvm_sequence_item;
    
    // Transaction fields
    rand bit [32-1:0]  addr;
    rand bit [32-1:0]  data;
    rand bit [4-1:0]  strb;
    rand axi_trans_type_e            trans_type;
    rand bit [2:0]                   prot;
    
    // Response fields
    bit [32-1:0]       rdata;
    axi_resp_e                       resp;
    
    // Constraints
    constraint addr_align_c {
        addr[1:0] == 2'b00;
    }
    
    constraint strb_default_c {
        soft strb == '1;
    }
    
    constraint prot_default_c {
        soft prot == 3'b000;
    }
    
    constraint valid_addr_c {
        addr inside {
            'h00,
            'h04,
            'h08
        };
    }
    
    `uvm_object_utils_begin(axi4lite_seq_item)
        `uvm_field_int(addr, UVM_ALL_ON)
        `uvm_field_int(data, UVM_ALL_ON)
        `uvm_field_int(strb, UVM_ALL_ON)
        `uvm_field_enum(axi_trans_type_e, trans_type, UVM_ALL_ON)
        `uvm_field_int(prot, UVM_ALL_ON)
        `uvm_field_int(rdata, UVM_ALL_ON)
        `uvm_field_enum(axi_resp_e, resp, UVM_ALL_ON)
    `uvm_object_utils_end
    
    function new(string name = "axi4lite_seq_item");
        super.new(name);
    endfunction
    
    virtual function string convert2string();
        return $sformatf("%s: addr=0x%0h data=0x%0h rdata=0x%0h resp=%s",
                        trans_type.name(), addr, data, rdata, resp.name());
    endfunction
    
endclass : axi4lite_seq_item