//------------------------------------------------------------------------------
// AXI4-Lite Environment - Generated by VerifAI
//------------------------------------------------------------------------------

class axi4lite_env extends uvm_env;
    `uvm_component_utils(axi4lite_env)
    
    axi4lite_agent      agent;
    axi4lite_scoreboard scoreboard;
    axi4lite_coverage   coverage;
    
    function new(string name = "axi4lite_env", uvm_component parent = null);
        super.new(name, parent);
    endfunction
    
    virtual function void build_phase(uvm_phase phase);
        super.build_phase(phase);
        agent      = axi4lite_agent::type_id::create("agent", this);
        scoreboard = axi4lite_scoreboard::type_id::create("scoreboard", this);
        coverage   = axi4lite_coverage::type_id::create("coverage", this);
    endfunction
    
    virtual function void connect_phase(uvm_phase phase);
        super.connect_phase(phase);
        agent.ap.connect(scoreboard.ap);
        agent.ap.connect(coverage.analysis_export);
    endfunction
endclass : axi4lite_env