//------------------------------------------------------------------------------
// AXI4-Lite Top Testbench - Generated by UVMForge
//------------------------------------------------------------------------------

`timescale 1ns/1ps

module top_tb;
    
    import uvm_pkg::*;
    `include "uvm_macros.svh"
    import axi4lite_pkg::*;
    
    logic clk;
    logic rst_n;
    
    initial begin
        clk = 0;
        forever #5 clk = ~clk;
    end
    
    initial begin
        rst_n = 1'b0;
        repeat (10) @(posedge clk);
        rst_n = 1'b1;
    end
    
    axi4lite_if vif(clk, rst_n);
    
    axi4lite_dut dut (
        .clk   (clk),
        .rst_n   (rst_n),
        .awaddr        (vif.awaddr),
        .awvalid       (vif.awvalid),
        .awready       (vif.awready),
        .awprot        (vif.awprot),
        .wdata         (vif.wdata),
        .wstrb         (vif.wstrb),
        .wvalid        (vif.wvalid),
        .wready        (vif.wready),
        .bresp         (vif.bresp),
        .bvalid        (vif.bvalid),
        .bready        (vif.bready),
        .araddr        (vif.araddr),
        .arvalid       (vif.arvalid),
        .arready       (vif.arready),
        .arprot        (vif.arprot),
        .rdata         (vif.rdata),
        .rresp         (vif.rresp),
        .rvalid        (vif.rvalid),
        .rready        (vif.rready)
    );
    
    initial begin
        uvm_config_db#(virtual axi4lite_if.master)::set(null, "*", "vif", vif.master);
        uvm_config_db#(virtual axi4lite_if.monitor)::set(null, "*", "vif", vif.monitor);
        run_test();
    end
    
    initial begin
        $dumpfile("axi4lite_tb.vcd");
        $dumpvars(0, top_tb);
    end
    
    initial begin
        #1ms;
        `uvm_fatal("TIMEOUT", "Test timed out!")
    end
    
endmodule : top_tb