//------------------------------------------------------------------------------
// I2C UVM Package
// Generated by UVMForge - Natural Language to UVM Testbench Generator
// Protocol: I2C (Inter-Integrated Circuit)
//------------------------------------------------------------------------------

`ifndef I2C_PKG_SV
`define I2C_PKG_SV

package i2c_master_i2c_pkg;
    
    import uvm_pkg::*;
    `include "uvm_macros.svh"
    
    //--------------------------------------------------------------------------
    // I2C Parameters
    //--------------------------------------------------------------------------
    parameter int I2C_DATA_WIDTH = 8;  // I2C always uses 8-bit data
    parameter int I2C_ADDR_WIDTH = 7;  // 7 or 10 bit
    parameter int I2C_CLOCK_FREQ = 100000;  // Hz
    
    // Timing parameters (in clock cycles at system clock)
    parameter int T_BUF   = 47;   // Bus free time
    parameter int T_HD_STA = 40; // START hold
    parameter int T_SU_STA = 47; // START setup
    parameter int T_SU_STO = 40; // STOP setup
    parameter int T_LOW   = 47;   // SCL low
    parameter int T_HIGH  = 40;  // SCL high
    
    //--------------------------------------------------------------------------
    // I2C Types
    //--------------------------------------------------------------------------
    
    // I2C operation type
    typedef enum bit {
        I2C_WRITE = 1'b0,
        I2C_READ  = 1'b1
    } i2c_rw_t;
    
    // I2C transfer result
    typedef enum bit [1:0] {
        I2C_ACK      = 2'b00,  // Acknowledge received
        I2C_NACK     = 2'b01,  // No acknowledge
        I2C_ARB_LOST = 2'b10,  // Arbitration lost
        I2C_TIMEOUT  = 2'b11   // Timeout
    } i2c_result_t;
    
    // I2C speed mode
    typedef enum bit [1:0] {
        I2C_STANDARD   = 2'b00,  // 100 kHz
        I2C_FAST       = 2'b01,  // 400 kHz
        I2C_FAST_PLUS  = 2'b10,  // 1 MHz
        I2C_HIGH_SPEED = 2'b11   // 3.4 MHz
    } i2c_speed_t;
    
    // I2C bus state
    typedef enum bit [2:0] {
        I2C_IDLE       = 3'b000,
        I2C_START      = 3'b001,
        I2C_ADDR       = 3'b010,
        I2C_DATA       = 3'b011,
        I2C_ACK_PHASE  = 3'b100,
        I2C_STOP       = 3'b101,
        I2C_REP_START  = 3'b110
    } i2c_state_t;
    
    //--------------------------------------------------------------------------
    // Include I2C Components
    //--------------------------------------------------------------------------
    `include "i2c_seq_item.sv"
    `include "i2c_driver.sv"
    `include "i2c_monitor.sv"
    `include "i2c_sequencer.sv"
    `include "i2c_agent.sv"
    `include "i2c_sequence_lib.sv"
    `include "i2c_scoreboard.sv"
    `include "i2c_coverage.sv"
    `include "i2c_env.sv"
    `include "i2c_base_test.sv"
    
endpackage : i2c_master_i2c_pkg

`endif // I2C_PKG_SV