//------------------------------------------------------------------------------
// UART Package
// Auto-generated by UVMForge
//------------------------------------------------------------------------------

package uart_pkg;
    
    // UVM imports
    import uvm_pkg::*;
    `include "uvm_macros.svh"
    
    // UART Parameters
    parameter int UART_DATA_BITS = 8;
    parameter int UART_STOP_BITS = 1;
    parameter int UART_BAUD_RATE = 115200;
    parameter int UART_BIT_PERIOD_NS = 8680;
    parameter int UART_FIFO_DEPTH = 16;
    
    // Parity type
    typedef enum {
        PARITY_NONE,
        PARITY_EVEN,
        PARITY_ODD,
        PARITY_MARK,
        PARITY_SPACE
    } parity_type_e;
    
    // Error types
    typedef enum {
        ERR_NONE,
        ERR_FRAME,
        ERR_PARITY,
        ERR_OVERRUN,
        ERR_BREAK
    } uart_error_e;
    
    // Transaction type
    typedef enum {
        UART_TX,
        UART_RX
    } uart_op_e;
    
    // Include all component files
    `include "uart_seq_item.sv"
    `include "uart_driver.sv"
    `include "uart_monitor.sv"
    `include "uart_sequencer.sv"
    `include "uart_agent.sv"
    `include "uart_sequence_lib.sv"
    `include "uart_scoreboard.sv"
    `include "uart_coverage.sv"
    `include "uart_env.sv"
    `include "uart_base_test.sv"
    
endpackage : uart_pkg